on:
  push:
    branches:
    - test

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@master
      with:
        token: ${{secrets.github_token}}
    - name: Print ENV
      uses: einaregilsson/print-environment@master
          
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Another step as an example
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: ${{needs.job1.outputs.build_number}}
    - name: Print ENV
      uses: einaregilsson/print-environment@master
